# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Collections
collections:
  policies:
    output: true

# Site settings
title: Romuald Ouattara
description: Personal website and blog.
url: "http://ouattararomuald.com"
show_downloads: true

# Theme configurations
repository: ouattararomuald/ouattararomuald.com
github:
  is_project_page: true
  repository_name: ouattararomuald.com
  source_zip_url: https://github.com/ouattararomuald/android-image-slider/archive/master.zip
  another_url: another value
maven:
  project_name: slider
  artifact_version: 1.0.0

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
